export default {
  USER_SET_AUTH_TOKEN: '@@USER/SET_AUTH_TOKEN',
  TIMELINE_CLEAR: '@@TIMELINE/CLEAR',
  API_GET_TIMELINE_LOAD: '@@API/GET_TIMELINE_LOAD',
  API_GET_TIMELINE_SUCCESS: '@@API/GET_TIMELINE_SUCCESS',
  API_GET_TIMELINE_FAILURE: '@@API/GET_TIMELINE_FAILURE',
};
